services:
  simulation:
    build: .
    image: mydolfinx:v0.9 
    volumes:
        - .:/app
    ports:
        - "8888:8888"
    working_dir: /app
    tty: true            
    stdin_open: true    
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
